### ISSUE TITLE
What coin...

### ISSUE THREAD

**Issue by nazariyv** [guptarohit/cryptoCMD#14]
<img src='https://i.ibb.co/nbzvDBX/Screenshot-from-2019-02-28-20-03-21.png'>

**Comment by nazariyv** [comment]
would be nice to know which coin please :)

**Comment by Boterbabbelaar** [comment]
I am also wondering, is there a way to skip such a coin when you are in a loop scraping the data from multiple coins?

Example code: 
 except InvalidCoinCode: Continue

**Comment by guptarohit** [comment]
@Boterbabbelaar Check the following snippet might be useful for your case:

```python
from cryptocmd import CmcScraper
from cryptocmd.utils import InvalidCoinCode

coins = ["BTC", "ETH", "RANDOMCODE", "XRP"]

for coin in coins:
    try:
        scraper = CmcScraper(coin, start_date="10-06-2019", end_date="15-06-2019")
        scraper.export("csv")
    except InvalidCoinCode as e:
        print(e)
        print("skipping: {}".format(coin))
        continue
```
:cheese: :sparkles:
