### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by mtr980** [guptarohit/cryptoCMD#15]
**This is a(n):**

- [ ] New feature
- [ ] Update to an existing feature
- [ x] Error
- [ ] Proposal to the Repository

**Details:**

> Hi,
> 
> Trying to run scrapper for multiple coins and getting the error.  Can I run scrapper for all coins in one go?

Code that I am trying:

```
scraper = CmcScraper('CS')
scraper.export('json', name='cs_all_time')
scraper = CmcScraper('PHX')
scraper.export('json', name='phx_all_time')
scraper = CmcScraper('DMT')
scraper.export('json', name='dmt_all_time')
scraper = CmcScraper('TEN')

```
ERROR

```
Traceback (most recent call last):
  File "/Users/scrapper.py", line 634, in <module>
    scraper.export('json', name='cs_all_time')
  File "/Users/.virtualenvs/lib/python3.7/site-packages/cryptocmd/core.py", line 206, in export
    data = self.get_data(format, **kwargs)
  File "/Users/.virtualenvs/lib/python3.7/site-packages/cryptocmd/core.py", line 104, in get_data
    self._download_data(**kwargs)
  File "/Users/.virtualenvs/lib/python3.7/site-packages/cryptocmd/core.py", line 83, in _download_data
    self.end_date, self.start_date, self.headers, self.rows = extract_data(table)
  File "/Users/.virtualenvs/lib/python3.7/site-packages/cryptocmd/utils.py", line 154, in extract_data
    end_date, start_date = rows[0][0], rows[-1][0]
IndexError: list index out of range
```

**Comment by guptarohit** [comment]
Hi @mtr980, I tried to run the code snippet you mentioned above, for me it seems to be working fine.
Please make sure you are using the latest version of the package, do `pip install -U cryptocmd` :sparkles: to update. 
Let me know if are still facing the issue. :peace_symbol:

**Comment by itzler** [comment]
Hi @guptarohit, I'm getting the same error as above. Seems to somewhat randomly stop processing pairs towards the end of the list.

Code I'm trying:

`token_list = ["AMPL", "DCR", "REN", "BTC", "ETH", "ATOM", "XTZ", "BNB", "MKR", "ZRX", "NMR", "GRIN", "REP"]
        for name in token_list:
            scraper = CmcScraper(name, "30-06-2019", "14-07-2019")
            scraper.export("csv", name= name) `

**Comment by aefremis** [comment]
I think the usse persists as it returns the same error. Even in the tutorial code . Maybe something changed in coinmarket?
