### ISSUE TITLE
Infinite loop while mass scraping data

### ISSUE THREAD

**Issue by Boterbabbelaar** [guptarohit/cryptoCMD#16]
**This is a(n):**

- [ ] New feature
- [ ] Update to an existing feature
- [x] Error
- [ ] Proposal to the Repository

**Details:**

I want to import the historical data to calculate volatility over the last period for all crypto coins. For this, I made a loop that goes through all coins and scrapes them one-by-one. Unfortunately, I already experienced problems with doing more than 10 requests within a minute. 

Now my question is: 
- Are there any limitation to scraping historical data? 
- Is there any way I can still scrape the historical data while respecting the limitations. 

for i in alldataCMC['Symbol']:
   scraper = CmcScraper(i)
   while True:
          try:
               data = scraper.get_dataframe()
          except IndexError:
               print("Downloading data of "+ i +" failed. Next try in 1 minute")
               time.sleep(10)
               continue
          break
   data = scraper.get_dataframe()
   data = data.set_index(['Date'])

This is the part of my code where it got stuck around #850 on coinmarketcap. I got the same symbol failing over and over again for 2 hours. 

I hope you can help me out.

**Comment by dc-aichara** [comment]
Hello! @Boterbabbelaar 
I have done similar project in fast.  I have calculated BVOC index of few cryptocurrencies. 
Answers to your queries. 
> Are there any limitation to scraping historical data?

There was no limitation till April, 2019.  Now, it seems that Coinmarketcap `restricted per minute requests to 10 from a IP address`.  
> is there any way I can still scrape the historical data while respecting the limitations.

Yes! There many way to extract historical data from coinmarketcap.  See a [simple example here](https://github.com/dc-aichara/Cryptocurrency-historical-data) . 
Feel free to reach out to [me](https://www.linkedin.com/in/dcaichara/) if you have any query.

**Comment by Boterbabbelaar** [comment]
Thank you for the reply, 

I fixed it by both making my list shorter as well as implementing a 70 seconds cooldown. Nevertheless the problem was that when extracting a lot of data from 100 coins+, there seems to be a limit around 800 requests as well. I was wondering if there is a way to solve this, anyway making the amount of requests less may do it for now.

**Comment by guptarohit** [comment]
Hi, @Boterbabbelaar seems like currently, the only option we have is to reduce the rate of request, as suggested by @dc-aichara.

@dc-aichara can you please share the page quoting `restricted per minute requests to 10 from an IP address` or is it something you found,  Thanks :+1: 

p.s. sorry for the late reply.

**Comment by dc-aichara** [comment]
@guptarohit 
>@dc-aichara can you please share the page quoting restricted per minute requests to 10 from an IP address or is it something you found, Thanks 👍

I found it.  Thanks.

**Comment by tmlee** [comment]
@guptarohit @dc-aichara alternatively you can consider our CoinGecko public API at https://www.coingecko.com/en/api

Our API is not that restrictive and open thereby currently used by many services out there.

Happy to answer any questions you may have!

**Comment by dc-aichara** [comment]
@tmlee Thanks for information. I have been using `pycoingecko` for long time.  👯‍♂
