### ISSUE TITLE
1 hour or 4 hour data

### ISSUE THREAD

**Issue by kubilaykilinc** [guptarohit/cryptoCMD#19]
How can we get data from specific time periods Ex: 30 m or 1 hour or 4 hour maybe 1 week 

**This is a(n):**

- [ ] New feature
- [ ] Update to an existing feature
- [ ] Error
- [x] Proposal to the Repository

**Details:**

**Comment by guptarohit** [comment]
Hi @kubilaykilinc, OHLCV data is not available for the time intervals you mentioned, on the coinmarketcap.com

Though, you can get it via their [API](https://coinmarketcap.com/api/documentation/v1/#operation/getV1CryptocurrencyOhlcvHistorical) if you buy the premium API [plan](https://coinmarketcap.com/api/features/). :v:
