### ISSUE TITLE
How to deal with Connection error

### ISSUE THREAD

**Issue by merjekrepo** [guptarohit/cryptoCMD#20]
**This is a(n):**

- [ ] New feature
- [x] Update to an existing feature
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

In the utils.py file, there is the function get_url_data(url). While extracting data, my application stops running when there is something wrong with the http connection. I get the error "Error message (get_url_data) :....". Everything is normal so far. But what I need is to continue, i.e. catching the exception in my source code and re-request data. Currently, that is not possible because of sys.exit(1). The get_url_data(url) function should have the flexibility of disabling this line of code. Also, what kind of exception is this exactly? It would be great to be more specific with it so that this exception can be raised and I can catch it in my application.

**Comment by guptarohit** [comment]
please check with new release and feel free to re-open issue if it persists
