### ISSUE TITLE
How to get price information of coins with same symbol

### ISSUE THREAD

**Issue by cxd1995** [guptarohit/cryptoCMD#21]
@guptarohit 

**This is a(n):**

- [ ] New feature
- [ ] Update to an existing feature
- [ ] Error
- [x] Proposal to the Repository

There are many coins with the same ticker symbol. For example, **UNUS SED LEO** and **LEOcoin** use the same ticker symbol **LEO**;  **Cosmos** and **Atomic Coin** use the same ticker symbol **ATOM**; **CyberMiles** and **Comet** use the same ticker symbol **CMT**. The circumstance is common for coins.
  
So I am wondering how to get the price information of these coins that have the same symbol?

**Comment by guptarohit** [comment]
@cxd1995 Thanks for pointing out this case :+1:

Currently, the only way I see to distinguish the coin with the same coin-code is by explicitly providing its coinmarketcap-id to fetch data. For example, **Atomic Coin** have cmc-id **_[atomic-wallet-coin](https://coinmarketcap.com/currencies/atomic-wallet-coin/)_** and **Cosmos** have cmc-id **_[cosmos](https://coinmarketcap.com/currencies/cosmos/)_**.
Let me know if you find any other solution. You can always send a PR :)
:octocat: :cake:

**Comment by cxd1995** [comment]
Will the scraper still works if the input is the coinmarketcap-id? It seems that the input of the scraper could only be the ticker symbol such as ETH, BTC. 

When I try to use the coinmarketcap-id such as atomic-wallet-coin and cosmos, the returned result is 
"This coin code is unavailable on "coinmarketcap.com"

**Comment by guptarohit** [comment]
No, it doesn't accept coinmarketcap-id as input currently, will need make changes for that.

**Comment by JuanRdBO** [comment]
Hello did you find a solution tot his yet? With more and more tokens getting added, it would make distinguishing between them that much easier. Any chance that token contract address could be a possible input to distinguish the tokens?

**Comment by ttozatto** [comment]
I forked the project and added an `id_number` parameter, so you can pass instead of `symbol`.

You can check the id here [https://web-api.coinmarketcap.com/v1/cryptocurrency/map?symbol=ATOM]()

You can clone the repository from here [https://github.com/ttozatto/cryptoCMD.git]()
