### ISSUE TITLE
Parameter,time interval, does not work

### ISSUE THREAD

**Issue by 0xtaosu** [guptarohit/cryptoCMD#23]
**This is a(n):**

- [ ] New feature
- [ ] Update to an existing feature
- [x] Error
- [ ] Proposal to the Repository

**Details:**

**Comment by guptarohit** [comment]
Hi @taosue, can please share same [mcve](https://stackoverflow.com/help/minimal-reproducible-example) if possible.

**Comment by guptarohit** [comment]
please check with new release and feel free to re-open issue if it persists
