### ISSUE TITLE
List out of range error

### ISSUE THREAD

**Issue by vioravis** [guptarohit/cryptoCMD#27]
**This is a(n):**

- [ ] New feature
- [ ] Update to an existing feature
- [x] Error
- [ ] Proposal to the Repository

**Details:**

When I try the following code:

scraper = CmcScraper("XRP", "15-10-2019", "25-10-2019")
df = scraper.get_dataframe()

This results in the following error:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-4-b99f6a0a400e> in <module>
      2 scraper = CmcScraper("XRP", "15-10-2019", "25-10-2019")
      3 # get dataframe for the data
----> 4 df = scraper.get_dataframe()

~/opt/anaconda3/lib/python3.7/site-packages/cryptocmd/core.py in get_dataframe(self, date_as_index, **kwargs)
    138             )
    139 
--> 140         self._download_data(**kwargs)
    141 
    142         dataframe = pd.DataFrame(data=self.rows, columns=self.headers)

~/opt/anaconda3/lib/python3.7/site-packages/cryptocmd/core.py in _download_data(self, **kwargs)
     81         print(self.coin_code, self.start_date, self.end_date)
     82 
---> 83         table = download_coin_data(self.coin_code, self.start_date, self.end_date)
     84 
     85         self.end_date, self.start_date, self.headers, self.rows = extract_data(table)

~/opt/anaconda3/lib/python3.7/site-packages/cryptocmd/utils.py in download_coin_data(coin_code, start_date, end_date)
     71         end_date = yesterday.strftime("%d-%m-%Y")
     72 
---> 73     coin_id = get_coin_id(coin_code)
     74 
     75     # Format the dates as required for the url.

~/opt/anaconda3/lib/python3.7/site-packages/cryptocmd/utils.py in get_coin_id(coin_code)
     50         raise InvalidCoinCode("'{}' coin code is unavailable on coinmarketcap.com".format(coin_code))
     51     except Exception as e:
---> 52         raise e
     53 
     54 

~/opt/anaconda3/lib/python3.7/site-packages/cryptocmd/utils.py in get_coin_id(coin_code)
     44 
     45         for _row in raw_data("tr")[1:]:
---> 46             symbol = _row.cssselect("td.text-left.col-symbol")[0].text_content()
     47             coin_id = _row.values()[0][3:]
     48             if symbol == coin_code:

IndexError: list index out of range

**Comment by davidfurrer** [comment]
can confirm, get same error
