### ISSUE TITLE
Error in utils.py

### ISSUE THREAD

**Issue by SarchB** [guptarohit/cryptoCMD#32]
Sorry, should probably not raise an issue but rather submit a commit, but don't work with girhub often and short on time. 

But I found that `coin_id = coin_link.values()[0].lstrip("/currencies/")[:-1]` in utils.py should be changed to `coin_id = coin_link.values()[0].replace("/currencies/","")[:-1]`

I discovered it while running into trouble trying to use your code for currency EOS. 

I found that '/currencies/eos' in your code resulted in 'os' as the coin_id, while it should be 'eos'. I thought it was a bug in Python but found it wasn't > https://bugs.python.org/issue5318

**Comment by guptarohit** [comment]
@SarchB, Thanks for raising the issue, fixed in new release :tada: please update.
