### ISSUE TITLE
 coin code is unavailable on coinmarketcap.com

### ISSUE THREAD

**Issue by cxd1995** [guptarohit/cryptoCMD#35]
**This is a(n):**

- [ ] New feature
- [ ] Update to an existing feature
- [x] Error
- [ ] Proposal to the Repository

**Details:**

I am going to fetch the historical price information of over four thousand tokens on coinmarketcap.com. The script works well to exact the first two hundred tokens ranking highest in coinmarketcap.com. But for all the rest tokens, it only returns the error **"[Coin Name] coin code is unavailable on coinmarketcap.com"** 
![image](https://user-images.githubusercontent.com/45622921/102784109-df19bb80-43d6-11eb-9961-81936ed8564f.png)

And I also noticed that the reason is that the page  https://coinmarketcap.com/all/views/all/ which is used to translate the coincode to a coinname now no longer displays all currencies and only displays the first 200 coins (#34 ).

**Comment by DJW41023** [comment]
I found another Crypto library which works:https://github.com/David-Woroniuk/Historic_Crypto

**Comment by guptarohit** [comment]
Thanks for reporting :hand: , This got fixed in new release, please update :v:
