### ISSUE TITLE
Open, Close, High, Low times

### ISSUE THREAD

**Issue by am2786** [guptarohit/cryptoCMD#38]
I see that your package has Open, Close, High, Low and Volume values for cryptocurrencies. Since trading for cryptos is always possible, what times do the Open and Close values correspond to?

**Comment by flxai** [comment]
CoinMarketCap itself defines Open and Close times as follows:

> **When does the market open and close? What timezone is it in?**
> The market opens at 12:00 AM (00:00) and closes at 11:59 PM (23:59) UTC time.
> For the Historical Tab of a Coin/Token, we take a snapshot when the market opens and when the market closes.
> Data is collected, recorded, and reported in UTC time unless otherwise specified.

([source](https://support.coinmarketcap.com/hc/en-us/articles/360016193231-Market-Open-and-Close-Times))
