### ISSUE TITLE
Same Symbol for coins

### ISSUE THREAD

**Issue by ElrondMcEnz** [guptarohit/cryptoCMD#41]
Hey Is there a workaround for coins with the same symbol? For example

Wonderland (TIME)
Chrono.tech (TIME)

**Comment by ttozatto** [comment]
I forked the project and added an `id_number` parameter, so you can pass instead of `symbol`.

You can check the id here [https://web-api.coinmarketcap.com/v1/cryptocurrency/map?symbol=TIME]()

You can clone the repository from here [https://github.com/ttozatto/cryptoCMD.git]()
