### ISSUE TITLE
Hello, I am trying to get historical data for multiple tokens but the process mentioned here seems to not be working. Can anyone please write the code for multiple tokens with an example of how to properly use it? Thanks

### ISSUE THREAD

**Issue by Faresearch** [guptarohit/cryptoCMD#54]
**This is a(n):**

- [ ] New feature
- [ ] Update to an existing feature
- [ ] Error
- [ ] Proposal to the Repository

**Details:**

**Comment by Qualzz** [comment]
Can you show what have you tried ?

**Comment by guptarohit** [comment]
please check with new release and feel free to re-open issue if it persists, and please share [mcve](https://stackoverflow.com/help/minimal-reproducible-example) if possible.
