### ISSUE TITLE
Bug - pandas datetime parse

### ISSUE THREAD

**Issue by grafa** [guptarohit/cryptoCMD#6]
When you call `pd.to_datetime()` you forgot to add `dayfirst=True` param. Data that come from CMC are in format DD-MM-YYYY and `pd.to_datetime()` defaults param `dayfirst` to False which leads to completely messed up data.

Just fixed that in my local virtualenv and it works flawlessly now.

Thank you.

**Comment by guptarohit** [comment]
Hi @grafa, thanks for finding this issue. Can you please explain a little bit about the case where you saw incorrect data if ```dayfirst``` param is not True.

**Comment by grafa** [comment]
I was fetching XRP historical data since I guess 1st Jan. 2015.
